### ISSUE TITLE
Is it possible to create an array of runningMedian to call them in a for loop ?

### ISSUE THREAD

**Issue by Speedy2k** [RobTillaart/RunningMedian#17] opened 2022-06-21 16:33 UTC
Hi, i need to create an array of running median to access them in a for loop, is it possible? Like this:

```cpp
RunningMedian outTempCMed[5];

setup(){
    for(size_t i = 0; i < 5; i++){
        outTempCMed[i] = RunningMedian(20);
    }
}
```
Is this something possible ??

Thanx a lot!

**Comment by RobTillaart** [comment] 2022-06-21 17:08
Thanks for this good question.
It should be possible, need to think about the exact syntax.

**Comment by RobTillaart** [comment] 2022-06-21 18:49
initializing could also be done 
```cpp
RunningMedian RM[4] = { RunningMedian(5),RunningMedian(5),RunningMedian(5),RunningMedian(5) };
```

**Comment by RobTillaart** [comment] 2022-06-21 19:04
If you use an array of pointers you can initiialize the array in **setup()**

See - https://github.com/RobTillaart/RunningMedian/tree/master/examples/RunningMedian_array_pointer

**Comment by RobTillaart** [comment] 2022-06-21 19:32
Good to hear it works,

**Comment by RobTillaart** [comment] 2022-06-23 05:37
AS the problem is solved I close the issue

**Closed by RobTillaart** 2022-06-23 05:37 UTC
Labels: question
